export const statusColors: Record<string, string> = {
  active: "bg-green-100 text-green-800",
  expired: "bg-red-100 text-red-800",
  pending: "bg-yellow-100 text-yellow-800",
  closed: "bg-gray-100 text-gray-800",
  on_hold: "bg-orange-100 text-orange-800",
}

export const documentCategories: Record<string, { label: string; color: string; icon: string }> = {
  trade_license: { label: "Trade License", color: "bg-blue-100 text-blue-800", icon: "TL" },
  visa: { label: "Visa / Residency", color: "bg-purple-100 text-purple-800", icon: "VS" },
  emirates_id: { label: "Emirates ID", color: "bg-teal-100 text-teal-800", icon: "EID" },
  passport: { label: "Passport (Front)", color: "bg-indigo-100 text-indigo-800", icon: "PP" },
  passport_back: { label: "Passport (Back)", color: "bg-indigo-50 text-indigo-700", icon: "PP" },
  national_id: { label: "National ID Card", color: "bg-sky-100 text-sky-800", icon: "NID" },
  labor_card: { label: "Labor Card", color: "bg-amber-100 text-amber-800", icon: "LC" },
  approved_labor_contract: { label: "Labor Contract", color: "bg-amber-50 text-amber-700", icon: "ALC" },
  establishment_card: { label: "Establishment Card", color: "bg-cyan-100 text-cyan-800", icon: "EC" },
  ejari: { label: "Ejari / Tawtheeq", color: "bg-lime-100 text-lime-800", icon: "EJ" },
  moa: { label: "Memorandum of Association", color: "bg-violet-100 text-violet-800", icon: "MOA" },
  poa: { label: "Power of Attorney", color: "bg-rose-100 text-rose-800", icon: "POA" },
  chamber_commerce: { label: "Chamber of Commerce", color: "bg-blue-50 text-blue-700", icon: "CC" },
  lease: { label: "Lease Agreement", color: "bg-stone-100 text-stone-800", icon: "LS" },
  immigration_card: { label: "Immigration Card", color: "bg-sky-100 text-sky-800", icon: "IM" },
  wps: { label: "WPS / SIF File", color: "bg-emerald-100 text-emerald-800", icon: "WPS" },
  noc: { label: "No Objection Certificate", color: "bg-fuchsia-100 text-fuchsia-800", icon: "NOC" },
  contract: { label: "Contract", color: "bg-orange-100 text-orange-800", icon: "CT" },
  health_insurance: { label: "Health Insurance", color: "bg-pink-100 text-pink-800", icon: "HI" },
  medical_insurance: { label: "Medical Insurance", color: "bg-pink-100 text-pink-800", icon: "MI" },
  medical_fitness: { label: "Medical Fitness", color: "bg-pink-50 text-pink-700", icon: "MF" },
  offer_letter: { label: "Offer Letter", color: "bg-yellow-100 text-yellow-800", icon: "OL" },
  salary_certificate: { label: "Salary Certificate", color: "bg-green-50 text-green-700", icon: "SC" },
  educational_degree: { label: "Educational Degree", color: "bg-violet-50 text-violet-700", icon: "ED" },
  financial: { label: "Financial / VAT", color: "bg-green-100 text-green-800", icon: "FIN" },
  legal: { label: "Legal Document", color: "bg-red-100 text-red-800", icon: "LG" },
  photo: { label: "Photo", color: "bg-slate-100 text-slate-800", icon: "PH" },
  other: { label: "Other", color: "bg-gray-100 text-gray-800", icon: "OT" },
}
