import type {
  Profile,
  Service,
  ServiceRequest,
  RequestTimeline,
  Payment,
  Notification,
} from "./types"

export function isDemoMode(): boolean {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  return !url || url === "your_supabase_url_here"
}

// ─── Demo Profiles ───────────────────────────────────────────────────────────

export const demoProfiles: Profile[] = [
  {
    id: "demo-client-001",
    email: "ahmed@company.ae",
    full_name: "Ahmed Al Mansoori",
    phone: "+971 50 123 4567",
    role: "client",
    avatar_url: null,
    company_id: "comp-001",
    is_active: true,
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2024-06-01T10:30:00Z",
  },
  {
    id: "demo-admin-001",
    email: "admin@yabs.ae",
    full_name: "Sarah Admin",
    phone: "+971 55 987 6543",
    role: "admin",
    avatar_url: null,
    company_id: null,
    is_active: true,
    created_at: "2024-01-01T08:00:00Z",
    updated_at: "2024-06-01T10:30:00Z",
  },
]

// ─── Demo Services ───────────────────────────────────────────────────────────

export const demoServices: Service[] = [
  {
    id: "svc-001",
    name: "Trade License New",
    category: "licensing",
    description: "New trade license issuance for mainland or free zone companies",
    price: 15000,
    estimated_days: 7,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-002",
    name: "Trade License Renewal",
    category: "licensing",
    description: "Annual trade license renewal with all government fees included",
    price: 12000,
    estimated_days: 5,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-003",
    name: "Trade License Amendment",
    category: "licensing",
    description: "Activity addition, removal, or modification on existing trade license",
    price: 5000,
    estimated_days: 3,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-004",
    name: "New Employment Visa",
    category: "visa",
    description: "Full employment visa processing including entry permit, status change, and stamping",
    price: 7500,
    estimated_days: 14,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-005",
    name: "Visa Renewal",
    category: "visa",
    description: "Employment visa renewal with medical, Emirates ID, and labor card",
    price: 5500,
    estimated_days: 10,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-006",
    name: "Visa Cancellation",
    category: "visa",
    description: "Employment visa cancellation and final settlement processing",
    price: 3000,
    estimated_days: 5,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-007",
    name: "Company Formation - Mainland",
    category: "business_setup",
    description: "Full mainland company setup including DED registration and approvals",
    price: 25000,
    estimated_days: 21,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-008",
    name: "Company Formation - Free Zone",
    category: "business_setup",
    description: "Free zone company formation with license and visa allocation",
    price: 30000,
    estimated_days: 14,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-009",
    name: "PRO Services Package",
    category: "business_setup",
    description: "Annual PRO services including government liaison and document processing",
    price: 18000,
    estimated_days: 0,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-010",
    name: "Document Attestation",
    category: "document_services",
    description: "Document attestation from MOFA, embassy, and notary public",
    price: 2000,
    estimated_days: 7,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-011",
    name: "Document Translation",
    category: "document_services",
    description: "Certified legal translation (Arabic-English) for official documents",
    price: 500,
    estimated_days: 2,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-012",
    name: "Emirates ID Application",
    category: "document_services",
    description: "New Emirates ID application or renewal processing",
    price: 370,
    estimated_days: 14,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-013",
    name: "VAT Registration",
    category: "accounting",
    description: "FTA VAT registration and TRN number issuance",
    price: 3000,
    estimated_days: 5,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-014",
    name: "VAT Return Filing",
    category: "accounting",
    description: "Quarterly VAT return preparation and filing with FTA",
    price: 2000,
    estimated_days: 3,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "svc-015",
    name: "Corporate Tax Registration",
    category: "accounting",
    description: "UAE corporate tax registration and compliance setup",
    price: 5000,
    estimated_days: 7,
    created_at: "2024-01-01T00:00:00Z",
  },
]

// ─── Demo Service Requests ───────────────────────────────────────────────────

export const demoRequests: ServiceRequest[] = [
  {
    id: "req-001",
    client_id: "demo-client-001",
    company_id: "comp-001",
    service_type: "Trade License Renewal",
    description: "Annual trade license renewal for Gulf Trading LLC. Current license expiring on March 31, 2026.",
    status: "in_progress",
    priority: "high",
    assigned_to: "demo-admin-001",
    notes: "Client requested expedited processing",
    due_date: "2026-03-31T00:00:00Z",
    completed_date: null,
    created_at: "2026-03-01T09:00:00Z",
    updated_at: "2026-03-15T14:30:00Z",
    client: demoProfiles[0],
    company: { name: "Gulf Trading LLC" },
    assignee: demoProfiles[1],
  },
  {
    id: "req-002",
    client_id: "demo-client-001",
    company_id: "comp-001",
    service_type: "New Employment Visa",
    description: "New employment visa for senior accountant position. Candidate: Mohammad Khan, Pakistani national.",
    status: "pending",
    priority: "medium",
    assigned_to: null,
    notes: null,
    due_date: "2026-04-15T00:00:00Z",
    completed_date: null,
    created_at: "2026-03-10T11:00:00Z",
    updated_at: "2026-03-10T11:00:00Z",
    client: demoProfiles[0],
    company: { name: "Gulf Trading LLC" },
  },
  {
    id: "req-003",
    client_id: "demo-client-001",
    company_id: "comp-002",
    service_type: "VAT Return Filing",
    description: "Q1 2026 VAT return filing for Emirates Zone Group.",
    status: "under_review",
    priority: "medium",
    assigned_to: "demo-admin-001",
    notes: "Awaiting final invoice from client",
    due_date: "2026-04-28T00:00:00Z",
    completed_date: null,
    created_at: "2026-03-05T08:30:00Z",
    updated_at: "2026-03-20T16:00:00Z",
    client: demoProfiles[0],
    company: { name: "Emirates Zone Group" },
    assignee: demoProfiles[1],
  },
  {
    id: "req-004",
    client_id: "demo-client-001",
    company_id: "comp-001",
    service_type: "Document Attestation",
    description: "MOFA attestation for board resolution and power of attorney documents.",
    status: "completed",
    priority: "low",
    assigned_to: "demo-admin-001",
    notes: "Documents collected and delivered to client",
    due_date: "2026-03-10T00:00:00Z",
    completed_date: "2026-03-08T15:00:00Z",
    created_at: "2026-02-25T10:00:00Z",
    updated_at: "2026-03-08T15:00:00Z",
    client: demoProfiles[0],
    company: { name: "Gulf Trading LLC" },
    assignee: demoProfiles[1],
  },
  {
    id: "req-005",
    client_id: "demo-client-001",
    company_id: "comp-003",
    service_type: "Visa Cancellation",
    description: "Visa cancellation for resigned employee Ravi Patel.",
    status: "rejected",
    priority: "low",
    assigned_to: "demo-admin-001",
    notes: "Employee has pending labor complaint. Cannot process cancellation until resolved.",
    due_date: null,
    completed_date: null,
    created_at: "2026-02-20T09:00:00Z",
    updated_at: "2026-02-22T11:00:00Z",
    client: demoProfiles[0],
    company: { name: "Al Noor Consulting" },
    assignee: demoProfiles[1],
  },
  {
    id: "req-006",
    client_id: "demo-client-001",
    company_id: "comp-004",
    service_type: "Company Formation - Free Zone",
    description: "New FZCO setup in Dubai Silicon Oasis for tech startup. 2 shareholders, 6 visa allocation.",
    status: "in_progress",
    priority: "urgent",
    assigned_to: "demo-admin-001",
    notes: "Initial approval received. Awaiting share capital deposit confirmation.",
    due_date: "2026-04-10T00:00:00Z",
    completed_date: null,
    created_at: "2026-03-12T10:00:00Z",
    updated_at: "2026-03-22T09:00:00Z",
    client: demoProfiles[0],
    company: { name: "Tech Ventures FZCO" },
    assignee: demoProfiles[1],
  },
]

// ─── Demo Timeline ───────────────────────────────────────────────────────────

export const demoTimeline: RequestTimeline[] = [
  {
    id: "tl-001",
    request_id: "req-001",
    status: "pending",
    message: "Service request submitted for trade license renewal.",
    created_by: "demo-client-001",
    created_at: "2026-03-01T09:00:00Z",
    creator: demoProfiles[0],
  },
  {
    id: "tl-002",
    request_id: "req-001",
    status: "in_progress",
    message: "Request assigned. Preparing renewal application documents.",
    created_by: "demo-admin-001",
    created_at: "2026-03-02T10:00:00Z",
    creator: demoProfiles[1],
  },
  {
    id: "tl-003",
    request_id: "req-001",
    status: "in_progress",
    message: "Application submitted to DED. Reference number: DED-2026-78432.",
    created_by: "demo-admin-001",
    created_at: "2026-03-15T14:30:00Z",
    creator: demoProfiles[1],
  },
  {
    id: "tl-004",
    request_id: "req-004",
    status: "pending",
    message: "Attestation request submitted with original documents.",
    created_by: "demo-client-001",
    created_at: "2026-02-25T10:00:00Z",
    creator: demoProfiles[0],
  },
  {
    id: "tl-005",
    request_id: "req-004",
    status: "in_progress",
    message: "Documents submitted to MOFA for attestation.",
    created_by: "demo-admin-001",
    created_at: "2026-02-27T11:00:00Z",
    creator: demoProfiles[1],
  },
  {
    id: "tl-006",
    request_id: "req-004",
    status: "completed",
    message: "Attestation completed. Documents ready for collection.",
    created_by: "demo-admin-001",
    created_at: "2026-03-08T15:00:00Z",
    creator: demoProfiles[1],
  },
  {
    id: "tl-007",
    request_id: "req-006",
    status: "pending",
    message: "Free zone company formation request submitted.",
    created_by: "demo-client-001",
    created_at: "2026-03-12T10:00:00Z",
    creator: demoProfiles[0],
  },
  {
    id: "tl-008",
    request_id: "req-006",
    status: "in_progress",
    message: "Initial approval obtained from DSO authority. Proceed with capital deposit.",
    created_by: "demo-admin-001",
    created_at: "2026-03-22T09:00:00Z",
    creator: demoProfiles[1],
  },
]

// ─── Demo Payments ───────────────────────────────────────────────────────────

export const demoPayments: Payment[] = [
  {
    id: "pay-001",
    request_id: "req-001",
    client_id: "demo-client-001",
    amount: 12000,
    vat_amount: 600,
    total_amount: 12600,
    status: "paid",
    method: "bank_transfer",
    description: "Trade License Renewal - Gulf Trading LLC",
    paid_at: "2026-03-02T12:00:00Z",
    created_at: "2026-03-01T09:00:00Z",
  },
  {
    id: "pay-002",
    request_id: "req-004",
    client_id: "demo-client-001",
    amount: 2000,
    vat_amount: 100,
    total_amount: 2100,
    status: "paid",
    method: "card",
    description: "Document Attestation - MOFA",
    paid_at: "2026-02-25T14:00:00Z",
    created_at: "2026-02-25T10:00:00Z",
  },
  {
    id: "pay-003",
    request_id: "req-006",
    client_id: "demo-client-001",
    amount: 30000,
    vat_amount: 1500,
    total_amount: 31500,
    status: "pending",
    method: "bank_transfer",
    description: "Company Formation - Tech Ventures FZCO (DSO)",
    paid_at: null,
    created_at: "2026-03-12T10:00:00Z",
  },
  {
    id: "pay-004",
    request_id: "req-003",
    client_id: "demo-client-001",
    amount: 2000,
    vat_amount: 100,
    total_amount: 2100,
    status: "pending",
    method: "online",
    description: "VAT Return Filing - Q1 2026 - Emirates Zone Group",
    paid_at: null,
    created_at: "2026-03-05T08:30:00Z",
  },
]

// ─── Demo Notifications ──────────────────────────────────────────────────────

export const demoNotifications: Notification[] = [
  {
    id: "notif-001",
    user_id: "demo-client-001",
    title: "License Renewal Update",
    message: "Your trade license renewal application has been submitted to DED. Reference: DED-2026-78432.",
    is_read: false,
    type: "info",
    link: "/dashboard/requests/req-001",
    created_at: "2026-03-15T14:30:00Z",
  },
  {
    id: "notif-002",
    user_id: "demo-client-001",
    title: "Payment Received",
    message: "Payment of AED 12,600 received for Trade License Renewal. Thank you!",
    is_read: true,
    type: "success",
    link: "/dashboard/payments",
    created_at: "2026-03-02T12:05:00Z",
  },
  {
    id: "notif-003",
    user_id: "demo-client-001",
    title: "Document Ready",
    message: "Your attested documents are ready for collection from our office.",
    is_read: false,
    type: "success",
    link: "/dashboard/requests/req-004",
    created_at: "2026-03-08T15:05:00Z",
  },
  {
    id: "notif-004",
    user_id: "demo-client-001",
    title: "Visa Request Rejected",
    message: "Visa cancellation for Ravi Patel has been rejected due to a pending labor complaint.",
    is_read: false,
    type: "error",
    link: "/dashboard/requests/req-005",
    created_at: "2026-02-22T11:05:00Z",
  },
  {
    id: "notif-005",
    user_id: "demo-client-001",
    title: "Upcoming Payment Due",
    message: "Payment of AED 31,500 for Tech Ventures FZCO formation is due. Please process at your earliest convenience.",
    is_read: false,
    type: "warning",
    link: "/dashboard/payments",
    created_at: "2026-03-20T08:00:00Z",
  },
]
